export const ROLES = [
  'Bagian Tata Pemerintahan',
  'Bagian Kesejahteraan Rakyat',
  'Bagian Hukum',
  'Bagian Kerja Sama',
  'Bagian Perekonomian',
  'Bagian Administrasi Pembangunan',
  'Bagian Pengadaan Barang dan Jasa',
  'Bagian Sumber Daya Alam',
  'Bagian Umum',
  'Bagian Organisasi',
  'Bagian Perencanaan dan Keuangan',
  'Bagian Protokol dan Komunikasi Pimpinan',
  'Sekretariat DPRD',
  'Inspektorat Daerah',
  'Dinas Pendidikan dan Kebudayaan',
  'Dinas Kesehatan',
  'Dinas Sosial',
  'Dinas Pekerjaan Umum',
  'Dinas Perkebunan',
  'Badan Riset dan Inovasi Daerah',
  'Badan Penanggulangan Bencana Daerah',
  'Dinas Pemadam Kebakaran dan Penyelamatan',
  'Dinas Ketahanan Pangan',
  'Dinas Pertanian dan Peternakan',
  'Badan Pendapatan Daerah',
  'Badan Kesatuan Bangsa dan Politik',
  'Satuan Polisi Pamong Praja',
  'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
  'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
  'Badan Pengelola Keuangan dan Aset Daerah',
  'Badan Perencanaan dan Pembangunan Daerah',
  'Dinas Perumahan dan Kawasan Permukiman',
  'Dinas Koperasi dan Usaha Kecil Menengah',
  'Dinas Lingkungan Hidup dan Kehutanan',
  'Dinas Pengendalian Penduduk dan Keluarga Berencana',
  'Dinas Pemberdayaan Perempuan dan Perlindungan Anak',
  'Dinas Pariwisata',
  'Dinas Kelautan dan Perikanan',
  'Dinas Kepemudaan dan Olahraga',
  'Dinas Kependudukan dan Pencatatan Sipil',
  'Dinas Transmigrasi dan Tenaga Kerja',
  'Dinas Pemberdayaan Masyarakat dan Desa',
  'Dinas Perhubungan',
  'Dinas Komunikasi dan Informatika',
  'Dinas Kearsipan dan Perpustakaan',
  'Dinas Pertanahan dan Penataan Ruang',
  'Dinas Perindustrian dan Perdagangan',
  'Rumah Sakit Umum Daerah Aji Muhammad Parikesit',
];

export const RISK_EVENTS = [
  { name: "Penyusunan dan pemeliharaan portofolio", impactAreas: [  "Program kerja atau sumber daya tidak sejalan dengan strategi dan prioritas organisasi.",
    "Terdapat duplikasi dalam inisatif",
    "Program utama yang dirancang membutuhkan waktu lama dalam implementasinya",
    "Sumberdaya yang dialokaskan tidak sejalan dengan kebutuhan bisnis"] },
  { name: "Manajemen siklus hidup program kerja atau proyek", impactAreas: [ "Proyek gagal tidak dihentikan",
    "Anggaran proyek melebihi anggaran",
    "Proyek TI internal terlambat",
    "Proyek TI outsource terlambat",
    "Tidak memiliki perencanaan memadai mengenai tahapan dan arahan yang harus dilakukan",
    "Tidak jelasnya kebutuhan dan ruang lingkup terhadap sistem",
    "Strategi dan tujuan tidak jelas ketika akan menerapkan sistem informasi",
    "Kurangnya dukungan dari pihak manajemen",
    "Program kerja atau proyek tidak mencapai target"] },
  { name: "Pembuatan keputusan investasi TI", impactAreas: [ "Pimpinan tidak memahami dalam pengambilan keputusan investasi TI (Perangkat lunak baru, peluang penggunaan teknologi baru)",
    "Perangkat lunak yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Infrastrukur yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Pengadaan atau pembelian perangkat lunak yang serupa"] },
  { name: "Keahlian dan keterampilan TI", impactAreas: ["Keterampilan staff TI tidak sesuai dengan teknologi",
    "Kurang memahami bisnis",
    "Kurangnya keterampilan untuk memenuhi kebutuhan bisnis",
    "Tidak memiliki kemampuan untuk recruit staff",
    "Kurangnya kemampuan investigasi proses recruitment, kurangnya pelatihan",
    "Keluarnya pegawai yang berkompetensi",
    "Ketergantungan terhadap orang atau pegawai (bukan sistem)",
    "Organisasi tidak memiliki kemampuan untuk meningkatkan keterampilan pegawai"] },
  { name: "Operasi yang dilakukan staf (human error dan niat jahat)", impactAreas: [ "Penyalahgunaan hak akses oleh staff",
    "Peralatan TI rusak secara tidak sengaja oleh staf",
    "Sistem error oleh staf",
    "Informasi yang dimasukkan salah oleh pengguna",
    "Data center dirusak oleh staf (sabotase)",
    "Pencurian data sensitive oleh staf",
    "Pencurian komponen infrastruktur utama oleh staf",
    "Komponen perangkat keras dikonfigurasi tidak benar",
    "Server kritis rusak pada NOC (insiden)",
    "Pemanfaatan sistem atau infrastruktur diluar kepentingan organisasi",
    "Perangkat keras dirusak dengan sengaja"] },
  { name: "Kerusakan, kebocoran dan akses informasi", impactAreas: [ "Komponen perangkat keras rusak yang menyebabkan kerusakan data",
    "Basis data rusak sehingga data tidak dapat diakses",
    "Portable media yang mengandung data sensitif menjadi hilang atau terbuka",
    "Data sensitif menjadi hilang atau terbuka karena ada serangan",
    "Backup media hilang atau backup tidak diperiksa dengan efektif",
    "Informasi sensitif menjadi terbuka secara tidak sengaja karena tidak mengikuti pedoman",
    "Data terubah secara tidak sengaja",
    "Informasi sensitif terbuka melalui email atau media sosial",
    "Informasi sensitif terkuak karena penyimpanan yang tidak efisien",
    "Informasi kompetitif/IP bocor yang disebabkan oleh staf yang keluar",
    "Data overflow (sebagai contoh big data)"] },
  { name: "Arsitektur", impactAreas: ["Enterprise arsitektur kompleks dan tidak fleksibel, sehingga menimbulkan kehilangan peluang bisnis",
    "EA tidak sesuai dengan tujuan dan tidak mendukung prioritas bisnis",
    "Kesalahan dalam mengadaptasi infrastruktur baru dalam satu waktu",
    "Kesalahan dalam mengadaptasi perangkat lunak baru dalam satu waktu"] },
  { name: "Infrastruktur", impactAreas: ["Infrastruktur baru yang dipasang menyebabkan sistem tidak stabil",
    "Sistem tidak dapat menanggulangi volume transaksi yang terus bertambah",
    "Sistem tidak dapat menanggulangi load ketika ada aplikasi baru",
    "Terdapat kegagalan utilitas (telepon, listrik) secara periodik terus menerus",
    "Sistem TI telah usang dan tidak sesuai dengan kebutuhan bisnis",
    "Perangkat keras gagal beroperasi karena panas yang berlebihan"] },
  { name: "Perangkat lunak", impactAreas: ["Ketidakmampuan dalam menggunakan SW untuk menghasilkan outcome yang diharapkan",
    "Modifikasi SW secara sengaja dapat menimbulkan fraud",
    "Modifikasi SW tidak sengaja menimbulkan hasil yang tidak diharapkan",
    "Kesalahan konfigurasi dan manajemen perubahan dapat terjadi",
    "Malfungsi dapat terjadi pada SW yang kritis",
    "Software sering bermasalah pada aplikasi yang penting",
    "Software aplikasi telah usang",
    "Ketidakmampuan mengembalikan software ke versi awal ketika telah diganti dengan versi terbaru yang bermasalah"] },
  { name: "Kepemilikan bisnis terhadap TI", impactAreas: ["Bisnis tidak menganggap perlunya akuntabilitas menggunakan TI",
    "Terdapat ketergantungan yang besar",
    "Penggunaan TI dan solusi sementara terhadap kebutuhan informasi namun memiliki kekurangan pada aspek keamanan",
    "Data tidak akurat",
    "Biaya yang besar dan penggunaan sumber daya yang tidak efisien",
    "Pengadaan TI tidak hemat biaya dan tidak efektif",
    "Kebutuhan yang tidak cukup menyebabkan SLA yang tidak efektif"] },
  { name: "Pemilihan/kinerja pemasok, kepatuhan terhadap kontrak, pemberhentian layanan dan pengalihan", impactAreas: [ "Kurangnya investigasi kepada pemasok terkait kemampuan finasialnya",
    "Kinerja outsourcing tidak dapat diandalkan untuk skala besar dan jangka waktu lama",
    "Ketidakpatuhan terhadap perjanjian penggunaan lisensi SW",
    "Ketidakmampuan mengalihkan ke pemasok lain ketika ada masalah pada pemasok yang sedang berjalan",
    "Layanan cloud yang telah digunakan oleh bisnis tanpa sepengetahuan TI sehingga akan menimbulkan kesulitan ketika akan diintegrasi dengan sistem layanan internal"] },
  { name: "Kepatuhan terhadap peraturan", impactAreas: ["Terdapat ketidakpatuhan terhadap peraturan",
    "Ketidakpedulian terhadap perubahan peraturan yang dapat mempengaruhi lingkungan operasional TI",
    "Regulator mencegah pertukaran data lintas batas tanpa kontrol yang cukup"] },
  { name: "Geopolitik", impactAreas: ["Tidak ada akses terhadap insiden yang mengganggu di tempat lain",
    "Intervensi pemerintah dan kebijakan nasional membatasi kemampuan layanan",
    "Target tindakan yang diambil tidak dapat memperbaiki kerusakan infrastruktur"] },
  { name: "Pencurian atau perusakan infrastruktur", impactAreas: [ "Pencurian terhadap peralatan yang mengandung data sensitif",
    "Pencurian terhadap perangkat server pengembangan",
    "Penghancuran pusat data (sabotase)",
    "Penghancuran terhadap perangkat pribadi staff"] },
  { name: "Malware", impactAreas: [ "Gangguan malware terhadap server operasional yang kritikal",
    "Notebook/Tablet sering terinfeksi malware",
    "Staff yang tidak puas menempatkan 'bom waktu' yang dapat mengakibatkan hilangnya data",
    "Data organisasi dicuri melalui akses ilegal dengan phishing attack"] },
  { name: "Serangan", impactAreas: ["Pengguna ilegal mencoba masuk ke dalam sistem",
    "Berhentinya layanan karena adanya DOS attack",
    "Perusakan website (deface)",
    "Pengintaian organisasi",
    "Serangan virus",
    "Hacktivism (aksi hacking untuk tujuan dengan motivasi politis atau sosial)"] },
  { name: "Aksi industri", impactAreas: [ "Fasilitas dan gedung tidak dapat diakses karena ada demo buruh",
    "Staf penting tidak dapat masuk kantor karena ada gangguan demo (khususnya pada transportasi)",
    "Pihak ketiga tidak dapat memberikan layanan karena ada halangan",
    "Tidak ada akses terhadap modal usaha karena ada gangguan pada industri perbankan"] },
  { name: "Lingkungan", impactAreas: ["Peralatan yang digunakan tidak ramah lingkungan (seperti penggunaan daya berlebih)"] },
  { name: "Bencana alam", impactAreas: ["Gempa bumi; tsunami; badai besar dan siklon tropis; kebakaran besar; banjir; water table"] },
  { name: "Inovasi", impactAreas: [    "Tren teknologi yang penting dan baru tidak dapat diidentifikasi",
    "Terjadi kegagalan ketika mengadopsi software baru"
] },
];


export const FREQUENCY_LEVELS = [
  'Hampir Tidak Terjadi',
  'Jarang Terjadi',
  'Kadang Terjadi',
  'Sering Terjadi',
  'Sangat Sering Terjadi',
];

export const IMPACT_MAGNITUDES = [
  'Tidak Signifikan',
  'Kurang Signifikan',
  'Cukup Signifikan',
  'Signifikan',
  'Sangat Signifikan',
];
