export const ROLES = [
  'Bagian Tata Pemerintahan',
  'Bagian Kesejahteraan Rakyat',
  'Bagian Hukum',
  'Bagian Kerja Sama',
  'Bagian Perekonomian',
  'Bagian Administrasi Pembangunan',
  'Bagian Pengadaan Barang dan Jasa',
  'Bagian Sumber Daya Alam',
  'Bagian Umum',
  'Bagian Organisasi',
  'Bagian Perencanaan dan Keuangan',
  'Bagian Protokol dan Komunikasi Pimpinan',
  'Sekretariat DPRD',
  'Inspektorat Daerah',
  'Dinas Pendidikan dan Kebudayaan',
  'Dinas Kesehatan',
  'Dinas Sosial',
  'Dinas Pekerjaan Umum',
  'Dinas Perkebunan',
  'Badan Riset dan Inovasi Daerah',
  'Badan Penanggulangan Bencana Daerah',
  'Dinas Pemadam Kebakaran dan Penyelamatan',
  'Dinas Ketahanan Pangan',
  'Dinas Pertanian dan Peternakan',
  'Badan Pendapatan Daerah',
  'Badan Kesatuan Bangsa dan Politik',
  'Satuan Polisi Pamong Praja',
  'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
  'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
  'Badan Pengelola Keuangan dan Aset Daerah',
  'Badan Perencanaan dan Pembangunan Daerah',
  'Dinas Perumahan dan Kawasan Permukiman',
  'Dinas Koperasi dan Usaha Kecil Menengah',
  'Dinas Lingkungan Hidup dan Kehutanan',
  'Dinas Pengendalian Penduduk dan Keluarga Berencana',
  'Dinas Pemberdayaan Perempuan dan Perlindungan Anak',
  'Dinas Pariwisata',
  'Dinas Kelautan dan Perikanan',
  'Dinas Kepemudaan dan Olahraga',
  'Dinas Kependudukan dan Pencatatan Sipil',
  'Dinas Transmigrasi dan Tenaga Kerja',
  'Dinas Pemberdayaan Masyarakat dan Desa',
  'Dinas Perhubungan',
  'Dinas Komunikasi dan Informatika',
  'Dinas Kearsipan dan Perpustakaan',
  'Dinas Pertanahan dan Penataan Ruang',
  'Dinas Perindustrian dan Perdagangan',
  'Rumah Sakit Umum Daerah Aji Muhammad Parikesit',
];

export const RISK_EVENTS = [
  'Minimnya SDM yang memahami Teknologi Informasi',
  'Proses Input data sering terlambat / terjadi kesalahan',
  'Data sektoral pemerintaahan tidak up-to-date / valid',
  'Produsen data tidak mau berbagi data',
  'Duplikasi data dengan value yang berbeda di dua aplikasi',
  'Kehilangan data di Server',
  'Ketergantungan dengan Vendor IT yang bermasalah',
  'Bahasa Pemrograman yang digunakan tidak sesuai standar technology pemda',
  'Pemadaman Listrik (listrik tidak stabil)',
  'Kebakaran',
  'Bencana Alam',
  'Dokumentasi teknis/panduan penggunaan sistem TIK tidak lengkap',
  'Aplikasi yang digunakan illegal (bajakan)/tidak berlisensi',
  'Komputer/laptop/PC terkena virus',
];

export const IMPACT_AREAS = [
  'Finansial',
  'Reputasi',
  'Kinerja',
  'Layanan Organisasi',
  'Operasional dan Aset TIK',
  'Hukum dan Regulasi',
  'Sumber Daya Manusia',
];

export const FREQUENCY_LEVELS = [
  'Hampir Tidak Terjadi',
  'Jarang Terjadi',
  'Kadang Terjadi',
  'Sering Terjadi',
  'Sangat Sering Terjadi',
];

export const IMPACT_MAGNITUDES = [
  'Tidak Signifikan',
  'Kurang Signifikan',
  'Cukup Signifikan',
  'Signifikan',
  'Sangat Signifikan',
];
