export const ROLES = [
  "Inspektorat Daerah",
  "Sekretariat Dewan Perwakilan Rakyat Daerah",
  "Badan Kepegawaian Dan Pengembangan Sumber Daya Manusia",
  "Badan Kesatuan Bangsa dan Politik",
  "Badan Pengelolaan Keuangan Dan Aset Daerah",
  "Badan Pendapatan Daerah",
  "Badan Perencanaan Pembangunan Daerah, Penelitian, Dan Pengembangan",
  "Dinas Pekerjaan Umum Dan Penataan Ruang",
  "Badan Penanggulangan Bencana Daerah",
  "Dinas Kebudayaan dan Pariwisata",
  "Dinas Kependudukan dan Pencatatan Sipil",
  "Dinas Kesehatan",
  "Dinas Ketahanan Pangan dan Pertanian",
  "Dinas Tenaga Kerja",
  "Dinas Komunikasi, Informatika, Statistik Dan Persandian",
  "Dinas Koperasi Usaha Kecil Dan Menengah",
  "Dinas Lingkungan Hidup",
  "Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk Dan Keluarga Berencana",
  "Dinas Kepemudaan Dan Olahraga",
  "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
  "Dinas Pendidikan",
  "Dinas Perindustrian Dan Perdagangan",
  "Dinas Perhubungan",
  "Dinas Perumahan Rakyat, Kawasan Permukiman Dan Pertanahan",
  "Dinas Sosial",
  "Dinas Perpustakaan Dan Arsip",
  "Satuan Polisi Pamong Praja Dan Pemadam Kebakaran",
  "Rumah Sakit Umum Daerah Ngudi Waluyo Wlingi",
  "Rumah Sakit Umum Daerah Srengat",
  "Kecamatan Kanigoro",
  "Kelurahan Satreyan",
  "Dinas Peternakan Dan Perikanan",
  "Bagian Organisasi",
  "Bagian Protokol dan Komunikasi Pimpinan",
  "Bagian Umum",
  "Bagian Perencanaan dan Keuangan",
  "Bagian Perekonomian",
  "Bagian Administrasi Pembangunan",
  "Bagian Pengadaan Barang dan Jasa",
  "Bagian Tata Pemerintahan",
  "Bagian Hukum",
  "Bagian Kesejahteraan Rakyat",
  "Penguji Coba",
  "Dinas Pemberdayaan Masyarakat Dan Desa"
];

export const RISK_EVENTS = [
  { name: "Penyusunan dan pemeliharaan portofolio", 
    impactAreas: [  "Program kerja atau sumber daya tidak sejalan dengan strategi dan prioritas organisasi.",
    "Terdapat duplikasi dalam inisatif",
    "Program utama yang dirancang membutuhkan waktu lama dalam implementasinya",
    "Sumberdaya yang dialokaskan tidak sejalan dengan kebutuhan bisnis"] },
  { name: "Manajemen siklus hidup program kerja atau proyek", 
    impactAreas: [ "Proyek gagal tidak dihentikan",
    "Anggaran proyek melebihi anggaran",
    "Proyek TI internal terlambat",
    "Proyek TI outsource terlambat",
    "Tidak memiliki perencanaan memadai mengenai tahapan dan arahan yang harus dilakukan",
    "Tidak jelasnya kebutuhan dan ruang lingkup terhadap sistem",
    "Strategi dan tujuan tidak jelas ketika akan menerapkan sistem informasi",
    "Kurangnya dukungan dari pihak manajemen",
    "Program kerja atau proyek tidak mencapai target"] },
  { name: "Pembuatan keputusan investasi TI", 
    impactAreas: [ "Pimpinan tidak memahami dalam pengambilan keputusan investasi TI (Perangkat lunak baru, peluang penggunaan teknologi baru)",
    "Perangkat lunak yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Infrastrukur yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Pengadaan atau pembelian perangkat lunak yang serupa"] },
  { name: "Keahlian dan keterampilan TI", 
    impactAreas: ["Keterampilan staff TI tidak sesuai dengan teknologi",
    "Kurang memahami bisnis",
    "Kurangnya keterampilan untuk memenuhi kebutuhan bisnis",
    "Tidak memiliki kemampuan untuk recruit staff",
    "Kurangnya kemampuan investigasi proses recruitment, kurangnya pelatihan",
    "Keluarnya pegawai yang berkompetensi",
    "Ketergantungan terhadap orang atau pegawai (bukan sistem)",
    "Organisasi tidak memiliki kemampuan untuk meningkatkan keterampilan pegawai"] },
  { name: "Operasi yang dilakukan staf (human error dan niat jahat)", 
    impactAreas: [ "Penyalahgunaan hak akses oleh staff",
    "Peralatan TI rusak secara tidak sengaja oleh staf",
    "Sistem error oleh staf",
    "Informasi yang dimasukkan salah oleh pengguna",
    "Data center dirusak oleh staf (sabotase)",
    "Pencurian data sensitive oleh staf",
    "Pencurian komponen infrastruktur utama oleh staf",
    "Komponen perangkat keras dikonfigurasi tidak benar",
    "Server kritis rusak pada NOC (insiden)",
    "Pemanfaatan sistem atau infrastruktur diluar kepentingan organisasi",
    "Perangkat keras dirusak dengan sengaja"] },
  { name: "Kerusakan, kebocoran dan akses informasi", 
    impactAreas: [ "Komponen perangkat keras rusak yang menyebabkan kerusakan data",
    "Basis data rusak sehingga data tidak dapat diakses",
    "Portable media yang mengandung data sensitif menjadi hilang atau terbuka",
    "Data sensitif menjadi hilang atau terbuka karena ada serangan",
    "Backup media hilang atau backup tidak diperiksa dengan efektif",
    "Informasi sensitif menjadi terbuka secara tidak sengaja karena tidak mengikuti pedoman",
    "Data terubah secara tidak sengaja",
    "Informasi sensitif terbuka melalui email atau media sosial",
    "Informasi sensitif terkuak karena penyimpanan yang tidak efisien",
    "Informasi kompetitif/IP bocor yang disebabkan oleh staf yang keluar",
    "Data overflow (sebagai contoh big data)"] },
  { name: "Arsitektur", 
    impactAreas: ["Enterprise arsitektur kompleks dan tidak fleksibel, sehingga menimbulkan kehilangan peluang bisnis",
    "EA tidak sesuai dengan tujuan dan tidak mendukung prioritas bisnis",
    "Kesalahan dalam mengadaptasi infrastruktur baru dalam satu waktu",
    "Kesalahan dalam mengadaptasi perangkat lunak baru dalam satu waktu"] },
  { name: "Infrastruktur", 
    impactAreas: ["Infrastruktur baru yang dipasang menyebabkan sistem tidak stabil",
    "Sistem tidak dapat menanggulangi volume transaksi yang terus bertambah",
    "Sistem tidak dapat menanggulangi load ketika ada aplikasi baru",
    "Terdapat kegagalan utilitas (telepon, listrik) secara periodik terus menerus",
    "Sistem TI telah usang dan tidak sesuai dengan kebutuhan bisnis",
    "Perangkat keras gagal beroperasi karena panas yang berlebihan"] },
  { name: "Perangkat lunak", 
    impactAreas: ["Ketidakmampuan dalam menggunakan SW untuk menghasilkan outcome yang diharapkan",
    "Modifikasi SW secara sengaja dapat menimbulkan fraud",
    "Modifikasi SW tidak sengaja menimbulkan hasil yang tidak diharapkan",
    "Kesalahan konfigurasi dan manajemen perubahan dapat terjadi",
    "Malfungsi dapat terjadi pada SW yang kritis",
    "Software sering bermasalah pada aplikasi yang penting",
    "Software aplikasi telah usang",
    "Ketidakmampuan mengembalikan software ke versi awal ketika telah diganti dengan versi terbaru yang bermasalah"] },
  { name: "Kepemilikan bisnis terhadap TI", 
    impactAreas: ["Bisnis tidak menganggap perlunya akuntabilitas menggunakan TI",
    "Terdapat ketergantungan yang besar",
    "Penggunaan TI dan solusi sementara terhadap kebutuhan informasi namun memiliki kekurangan pada aspek keamanan",
    "Data tidak akurat",
    "Biaya yang besar dan penggunaan sumber daya yang tidak efisien",
    "Pengadaan TI tidak hemat biaya dan tidak efektif",
    "Kebutuhan yang tidak cukup menyebabkan SLA yang tidak efektif"] },
  { name: "Pemilihan/kinerja pemasok, kepatuhan terhadap kontrak, pemberhentian layanan dan pengalihan", 
    impactAreas: [ "Kurangnya investigasi kepada pemasok terkait kemampuan finasialnya",
    "Kinerja outsourcing tidak dapat diandalkan untuk skala besar dan jangka waktu lama",
    "Ketidakpatuhan terhadap perjanjian penggunaan lisensi SW",
    "Ketidakmampuan mengalihkan ke pemasok lain ketika ada masalah pada pemasok yang sedang berjalan",
    "Layanan cloud yang telah digunakan oleh bisnis tanpa sepengetahuan TI sehingga akan menimbulkan kesulitan ketika akan diintegrasi dengan sistem layanan internal"] },
  { name: "Kepatuhan terhadap peraturan", 
    impactAreas: ["Terdapat ketidakpatuhan terhadap peraturan",
    "Ketidakpedulian terhadap perubahan peraturan yang dapat mempengaruhi lingkungan operasional TI",
    "Regulator mencegah pertukaran data lintas batas tanpa kontrol yang cukup"] },
  { name: "Geopolitik", 
    impactAreas: ["Tidak ada akses terhadap insiden yang mengganggu di tempat lain",
    "Intervensi pemerintah dan kebijakan nasional membatasi kemampuan layanan",
    "Target tindakan yang diambil tidak dapat memperbaiki kerusakan infrastruktur"] },
  { name: "Pencurian atau perusakan infrastruktur", 
    impactAreas: [ "Pencurian terhadap peralatan yang mengandung data sensitif",
    "Pencurian terhadap perangkat server pengembangan",
    "Penghancuran pusat data (sabotase)",
    "Penghancuran terhadap perangkat pribadi staff"] },
  { name: "Malware", 
    impactAreas: [ "Gangguan malware terhadap server operasional yang kritikal",
    "Notebook/Tablet sering terinfeksi malware",
    "Staff yang tidak puas menempatkan 'bom waktu' yang dapat mengakibatkan hilangnya data",
    "Data organisasi dicuri melalui akses ilegal dengan phishing attack"] },
  { name: "Serangan", 
    impactAreas: ["Pengguna ilegal mencoba masuk ke dalam sistem",
    "Berhentinya layanan karena adanya DOS attack",
    "Perusakan website (deface)",
    "Pengintaian organisasi",
    "Serangan virus",
    "Hacktivism (aksi hacking untuk tujuan dengan motivasi politis atau sosial)"] },
  { name: "Aksi industri", 
    impactAreas: [ "Fasilitas dan gedung tidak dapat diakses karena ada demo buruh",
    "Staf penting tidak dapat masuk kantor karena ada gangguan demo (khususnya pada transportasi)",
    "Pihak ketiga tidak dapat memberikan layanan karena ada halangan",
    "Tidak ada akses terhadap modal usaha karena ada gangguan pada industri perbankan"] },
  { name: "Lingkungan", 
    impactAreas: ["Peralatan yang digunakan tidak ramah lingkungan (seperti penggunaan daya berlebih)"] },
  { name: "Bencana alam", 
    impactAreas: ["Gempa bumi; tsunami; badai besar dan siklon tropis; kebakaran besar; banjir; water table"] },
  { name: "Inovasi", 
    impactAreas: ["Tren teknologi yang penting dan baru tidak dapat diidentifikasi",
    "Terjadi kegagalan ketika mengadopsi software baru"
] },
];


export const FREQUENCY_LEVELS = [
  'Hampir Tidak Terjadi',
  'Jarang Terjadi',
  'Kadang Terjadi',
  'Sering Terjadi',
  'Sangat Sering Terjadi',
];

export const IMPACT_MAGNITUDES = [
  'Tidak Signifikan',
  'Kurang Signifikan',
  'Cukup Signifikan',
  'Signifikan',
  'Sangat Signifikan',
];

export const IMPACT_AREAS = [
    "Program kerja atau sumber daya tidak sejalan dengan strategi dan prioritas organisasi.",
    "Terdapat duplikasi dalam inisatif",
    "Program utama yang dirancang membutuhkan waktu lama dalam implementasinya",
    "Sumberdaya yang dialokaskan tidak sejalan dengan kebutuhan bisnis",
    "Proyek gagal tidak dihentikan",
    "Anggaran proyek melebihi anggaran",
    "Proyek TI internal terlambat",
    "Proyek TI outsource terlambat",
    "Tidak memiliki perencanaan memadai mengenai tahapan dan arahan yang harus dilakukan",
    "Tidak jelasnya kebutuhan dan ruang lingkup terhadap sistem",
    "Strategi dan tujuan tidak jelas ketika akan menerapkan sistem informasi",
    "Kurangnya dukungan dari pihak manajemen",
    "Program kerja atau proyek tidak mencapai target",
    "Pimpinan tidak memahami dalam pengambilan keputusan investasi TI (Perangkat lunak baru, peluang penggunaan teknologi baru)",
    "Perangkat lunak yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Infrastrukur yang salah, baik dalam tingginya biaya, performa, fitur, kompabilitas dalam implementasinya",
    "Pengadaan atau pembelian perangkat lunak yang serupa",
    "Keterampilan staff TI tidak sesuai dengan teknologi",
    "Kurang memahami bisnis",
    "Kurangnya keterampilan untuk memenuhi kebutuhan bisnis",
    "Tidak memiliki kemampuan untuk recruit staff",
    "Kurangnya kemampuan investigasi proses recruitment, kurangnya pelatihan",
    "Keluarnya pegawai yang berkompetensi",
    "Ketergantungan terhadap orang atau pegawai (bukan sistem)",
    "Organisasi tidak memiliki kemampuan untuk meningkatkan keterampilan pegawai",
    "Penyalahgunaan hak akses oleh staff",
    "Peralatan TI rusak secara tidak sengaja oleh staf",
    "Sistem error oleh staf",
    "Informasi yang dimasukkan salah oleh pengguna",
    "Data center dirusak oleh staf (sabotase)",
    "Pencurian data sensitive oleh staf",
    "Pencurian komponen infrastruktur utama oleh staf",
    "Komponen perangkat keras dikonfigurasi tidak benar",
    "Server kritis rusak pada NOC (insiden)",
    "Pemanfaatan sistem atau infrastruktur diluar kepentingan organisasi",
    "Perangkat keras dirusak dengan sengaja",
    "Komponen perangkat keras rusak yang menyebabkan kerusakan data",
    "Basis data rusak sehingga data tidak dapat diakses",
    "Portable media yang mengandung data sensitif menjadi hilang atau terbuka",
    "Data sensitif menjadi hilang atau terbuka karena ada serangan",
    "Backup media hilang atau backup tidak diperiksa dengan efektif",
    "Informasi sensitif menjadi terbuka secara tidak sengaja karena tidak mengikuti pedoman",
    "Data terubah secara tidak sengaja",
    "Informasi sensitif terbuka melalui email atau media sosial",
    "Informasi sensitif terkuak karena penyimpanan yang tidak efisien",
    "Informasi kompetitif/IP bocor yang disebabkan oleh staf yang keluar",
    "Data overflow (sebagai contoh big data)",
    "Enterprise arsitektur kompleks dan tidak fleksibel, sehingga menimbulkan kehilangan peluang bisnis",
    "EA tidak sesuai dengan tujuan dan tidak mendukung prioritas bisnis",
    "Kesalahan dalam mengadaptasi infrastruktur baru dalam satu waktu",
    "Kesalahan dalam mengadaptasi perangkat lunak baru dalam satu waktu",
    "Infrastruktur baru yang dipasang menyebabkan sistem tidak stabil",
    "Sistem tidak dapat menanggulangi volume transaksi yang terus bertambah",
    "Sistem tidak dapat menanggulangi load ketika ada aplikasi baru",
    "Terdapat kegagalan utilitas (telepon, listrik) secara periodik terus menerus",
    "Sistem TI telah usang dan tidak sesuai dengan kebutuhan bisnis",
    "Perangkat keras gagal beroperasi karena panas yang berlebihan",
    "Ketidakmampuan dalam menggunakan SW untuk menghasilkan outcome yang diharapkan",
    "Modifikasi SW secara sengaja dapat menimbulkan fraud",
    "Modifikasi SW tidak sengaja menimbulkan hasil yang tidak diharapkan",
    "Kesalahan konfigurasi dan manajemen perubahan dapat terjadi",
    "Malfungsi dapat terjadi pada SW yang kritis",
    "Software sering bermasalah pada aplikasi yang penting",
    "Software aplikasi telah usang",
    "Ketidakmampuan mengembalikan software ke versi awal ketika telah diganti dengan versi terbaru yang bermasalah",
    "Bisnis tidak menganggap perlunya akuntabilitas menggunakan TI",
    "Terdapat ketergantungan yang besar",
    "Penggunaan TI dan solusi sementara terhadap kebutuhan informasi namun memiliki kekurangan pada aspek keamanan",
    "Data tidak akurat",
    "Biaya yang besar dan penggunaan sumber daya yang tidak efisien",
    "Pengadaan TI tidak hemat biaya dan tidak efektif",
    "Kebutuhan yang tidak cukup menyebabkan SLA yang tidak efektif",
    "Kurangnya investigasi kepada pemasok terkait kemampuan finasialnya",
    "Kinerja outsourcing tidak dapat diandalkan untuk skala besar dan jangka waktu lama",
    "Ketidakpatuhan terhadap perjanjian penggunaan lisensi SW",
    "Ketidakmampuan mengalihkan ke pemasok lain ketika ada masalah pada pemasok yang sedang berjalan",
    "Layanan cloud yang telah digunakan oleh bisnis tanpa sepengetahuan TI sehingga akan menimbulkan kesulitan ketika akan diintegrasi dengan sistem layanan internal",
    "Terdapat ketidakpatuhan terhadap peraturan",
    "Ketidakpedulian terhadap perubahan peraturan yang dapat mempengaruhi lingkungan operasional TI",
    "Regulator mencegah pertukaran data lintas batas tanpa kontrol yang cukup",
    "Tidak ada akses terhadap insiden yang mengganggu di tempat lain",
    "Intervensi pemerintah dan kebijakan nasional membatasi kemampuan layanan",
    "Target tindakan yang diambil tidak dapat memperbaiki kerusakan infrastruktur",
    "Pencurian terhadap peralatan yang mengandung data sensitif",
    "Pencurian terhadap perangkat server pengembangan",
    "Penghancuran pusat data (sabotase)",
    "Penghancuran terhadap perangkat pribadi staff",
    "Gangguan malware terhadap server operasional yang kritikal",
    "Notebook/Tablet sering terinfeksi malware",
    "Staff yang tidak puas menempatkan 'bom waktu' yang dapat mengakibatkan hilangnya data",
    "Data organisasi dicuri melalui akses ilegal dengan phishing attack",
    "Pengguna ilegal mencoba masuk ke dalam sistem",
    "Berhentinya layanan karena adanya DOS attack",
    "Perusakan website (deface)",
    "Pengintaian organisasi",
    "Serangan virus",
    "Hacktivism (aksi hacking untuk tujuan dengan motivasi politis atau sosial)",
    "Fasilitas dan gedung tidak dapat diakses karena ada demo buruh",
    "Staf penting tidak dapat masuk kantor karena ada gangguan demo (khususnya pada transportasi)",
    "Pihak ketiga tidak dapat memberikan layanan karena ada halangan",
    "Tidak ada akses terhadap modal usaha karena ada gangguan pada industri perbankan",
    "Peralatan yang digunakan tidak ramah lingkungan (seperti penggunaan daya berlebih)",
    "Gempa bumi; tsunami; badai besar dan siklon tropis; kebakaran besar; banjir; water table",
    "Tren teknologi yang penting dan baru tidak dapat diidentifikasi",
    "Terjadi kegagalan ketika mengadopsi software baru"
];

export const ORGANIZATIONAL_CONTROLS = [
  "5.1 Kebijakan untuk keamanan informasi",
  "5.2 Peran dan tanggung jawab keamanan informasi",
  "5.3 Pemisahan tugas",
  "5.4 Tanggung jawab manajemen",
  "5.5 Kontak dengan pihak berwenang",
  "5.6 Kontak dengan kelompok minat khusus",
  "5.7 Intelijen ancaman",
  "5.8 Keamanan informasi dalam manajemen proyek",
  "5.9 Inventarisasi informasi dan aset terkait lainnya",
  "5.10 Penggunaan informasi dan aset terkait lainnya yang dapat diterima",
  "5.11 Pengembalian aset",
  "5.12 Klasifikasi informasi",
  "5.13 Pelabelan informasi",
  "5.14 Transfer informasi",
  "5.15 Kontrol akses",
  "5.16 Manajemen identitas",
  "5.17 Informasi otentikasi",
  "5.18 Hak akses",
  "5.19 Keamanan informasi dalam hubungan pemasok",
  "5.20 Mengatasi keamanan informasi dalam perjanjian pemasok",
  "5.21 Mengelola keamanan informasi dalam rantai pasokan TIK",
  "5.22 Memantau, meninjau, dan mengubah manajemen layanan pemasok",
  "5.23 Keamanan informasi untuk penggunaan layanan cloud",
  "5.24 Perencanaan dan persiapan manajemen insiden keamanan informasi",
  "5.25 Penilaian dan keputusan tentang peristiwa keamanan informasi",
  "5.26 Tanggapan terhadap insiden keamanan informasi",
  "5.27 Belajar dari insiden keamanan informasi",
  "5.28 Pengumpulan bukti",
  "5.29 Keamanan informasi selama gangguan",
  "5.30 Kesiapan TIK untuk kelangsungan bisnis",
  "5.31 Persyaratan hukum, undang-undang, peraturan, dan kontrak",
  "5.32 Hak kekayaan intelektual",
  "5.33 Perlindungan catatan",
  "5.34 Privasi dan perlindungan PII",
  "5.35 Tinjauan independen terhadap keamanan informasi",
  "5.36 Kepatuhan terhadap kebijakan, aturan, dan standar untuk keamanan informasi",
  "5.37 Prosedur operasi terdokumentasi"
];

export const PEOPLE_CONTROLS = [
  "6.1 Penyaringan",
  "6.2 Syarat dan ketentuan kerja",
  "6.3 Kesadaran, pendidikan dan pelatihan keamanan informasi",
  "6.4 Proses pendisiplinan",
  "6.5 Tanggung Jawab Setelah Pemutusan Hubungan Kerja atau Perubahan Pekerjaan",
  "6.6 Perjanjian kerahasiaan atau tidak mengungkapkan",
  "6.7 Kerja jarak jauh",
  "6.8 Pelaporan peristiwa keamanan informasi"
];

export const MITIGATION_OPTIONS = [
  "Eskalasi Risiko",
  "Eksploitasi Risiko",
  "Peningkatan Risiko",
  "Pembagian Risiko",
  "Penerimaan Risiko"
];
