
export const ROLES = [
  "Inspektorat Daerah",
  "Sekretariat Dewan Perwakilan Rakyat Daerah",
  "Badan Kepegawaian Dan Pengembangan Sumber Daya Manusia",
  "Badan Kesatuan Bangsa dan Politik",
  "Badan Pengelolaan Keuangan Dan Aset Daerah",
  "Badan Pendapatan Daerah",
  "Badan Perencanaan Pembangunan Daerah, Penelitian, Dan Pengembangan",
  "Dinas Pekerjaan Umum Dan Penataan Ruang",
  "Badan Penanggulangan Bencana Daerah",
  "Dinas Kebudayaan dan Pariwisata",
  "Dinas Kependudukan dan Pencatatan Sipil",
  "Dinas Kesehatan",
  "Dinas Ketahanan Pangan dan Pertanian",
  "Dinas Tenaga Kerja",
  "Dinas Komunikasi, Informatika, Statistik Dan Persandian",
  "Dinas Koperasi Usaha Kecil Dan Menengah",
  "Dinas Lingkungan Hidup",
  "Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk Dan Keluarga Berencana",
  "Dinas Kepemudaan Dan Olahraga",
  "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
  "Dinas Pendidikan",
  "Dinas Perindustrian Dan Perdagangan",
  "Dinas Perhubungan",
  "Dinas Perumahan Rakyat, Kawasan Permukiman Dan Pertanahan",
  "Dinas Sosial",
  "Dinas Perpustakaan Dan Arsip",
  "Satuan Polisi Pamong Praja Dan Pemadam Kebakaran",
  "Rumah Sakit Umum Daerah Ngudi Waluyo Wlingi",
  "Rumah Sakit Umum Daerah Srengat",
  "Kecamatan Kanigoro",
  "Kelurahan Satreyan",
  "Dinas Peternakan Dan Perikanan",
  "Bagian Organisasi",
  "Bagian Protokol dan Komunikasi Pimpinan",
  "Bagian Umum",
  "Bagian Perencanaan dan Keuangan",
  "Bagian Perekonomian",
  "Bagian Administrasi Pembangunan",
  "Bagian Pengadaan Barang dan Jasa",
  "Bagian Tata Pemerintahan",
  "Bagian Hukum",
  "Bagian Kesejahteraan Rakyat",
  "Penguji Coba",
  "Dinas Pemberdayaan Masyarakat Dan Desa"
];
